import { useState } from 'react'
import { Activity, AlertTriangle, Building2, ChevronRight, CircleCheck, Download, FileText, Filter, Gauge, GitFork, MapPin, Network, Phone, Plus, Search, Shield, Smartphone, User, Users, X } from 'lucide-react'

type Toast=(s:string)=>void
const dimensions=[['Identity anomalies',82,'Passport mismatch and duplicate telephone'],['Case history',67,'Linked to two active investigations'],['Relationships',61,'Three monitored associations'],['Travel patterns',46,'Recurring cross-border travel'],['Financial indicators',32,'No material anomaly established'],['Online activity',24,'Limited authorized observations']]
const nodes=[
 {id:'musa',label:'Musa Ibrahim',sub:'SOI-04182',type:'person',x:50,y:47,icon:User},
 {id:'ibrahim',label:'Ibrahim Lawal',sub:'SOI-03971',type:'person',x:21,y:24,icon:User},
 {id:'incident',label:'INC-2026-0891',sub:'Infrastructure',type:'incident',x:78,y:22,icon:AlertTriangle},
 {id:'phone',label:'+234 803•••7821',sub:'Shared phone',type:'device',x:82,y:69,icon:Phone},
 {id:'address',label:'12 Zoo Road',sub:'Shared address',type:'location',x:26,y:76,icon:MapPin},
 {id:'org',label:'Kano Transit Ltd',sub:'Organization',type:'org',x:52,y:12,icon:Building2},
]
const links=[['musa','ibrahim'],['musa','incident'],['musa','phone'],['musa','address'],['musa','org'],['ibrahim','address'],['incident','phone']]
function Pill({children,tone='neutral'}:{children:React.ReactNode,tone?:string}){return <span className={`pill ${tone}`}>{children}</span>}

function RelationshipMap({toast}:{toast:Toast}){const [selected,setSelected]=useState(nodes[0]);const nodeMap=Object.fromEntries(nodes.map(n=>[n.id,n]));return <div className="relationship-layout"><div className="card graph-card"><div className="analysis-toolbar"><div className="graph-search"><Search/><input placeholder="Add person, incident, phone..."/><button><Plus/></button></div><div><button className="secondary"><Filter/> Filter</button><button className="secondary" onClick={()=>toast('Relationship map exported')}><Download/> Export</button></div></div><div className="graph-canvas"><svg className="graph-links" viewBox="0 0 100 100" preserveAspectRatio="none">{links.map(([a,b])=><line key={a+b} x1={nodeMap[a].x} y1={nodeMap[a].y} x2={nodeMap[b].x} y2={nodeMap[b].y}/>)}</svg>{nodes.map(n=><button key={n.id} style={{left:`${n.x}%`,top:`${n.y}%`}} className={`graph-node ${n.type} ${selected.id===n.id?'selected':''}`} onClick={()=>setSelected(n)}><i><n.icon/></i><b>{n.label}</b><small>{n.sub}</small></button>)}<div className="graph-legend"><span><i className="person"/>Person</span><span><i className="incident"/>Incident</span><span><i className="device"/>Phone/device</span><span><i className="location"/>Location</span></div></div></div><div className="card evidence-panel"><div className="evidence-head"><span>SELECTED ENTITY</span><h3>{selected.label}</h3><p>{selected.sub}</p></div><div className="evidence-score"><Shield/><div><b>Evidence-supported link</b><span>Confidence: High</span></div><Pill tone="success">Confirmed</Pill></div><h4>Relationships</h4>{selected.id==='musa'?<>{[['Ibrahim Lawal','Associate · 4 interactions'],['INC-2026-0891','Linked subject'],['12 Zoo Road','Previous address'],['Kano Transit Ltd','Former employee']].map((r,i)=><button className="relation-row" key={r[0]} onClick={()=>setSelected(nodes[i+1])}><i>{i===0?<Users/>:i===1?<AlertTriangle/>:i===2?<MapPin/>:<Building2/>}</i><div><b>{r[0]}</b><span>{r[1]}</span></div><ChevronRight/></button>)}</>:<button className="relation-row" onClick={()=>setSelected(nodes[0])}><i><User/></i><div><b>Musa Ibrahim</b><span>Linked entity</span></div><ChevronRight/></button>}<h4>Supporting evidence</h4><div className="source"><FileText/><div><b>Field report FR-2281</b><span>Source reliability A · Confirmed</span></div></div><div className="source"><Smartphone/><div><b>Contact record</b><span>Verified 29 Aug 2026</span></div></div><button className="primary full" onClick={()=>toast(`${selected.label} added to Information Cart`)}><Plus/> Add to Information Cart</button></div></div>}

function RiskAnalysis({toast}:{toast:Toast}){return <div className="risk-workspace"><div className="card risk-overview"><div className="analysis-subhead"><div><span>SUBJECT ASSESSMENT</span><h3>Musa Ibrahim</h3><p>SOI-04182 · Calculated 01 Sep 2026</p></div><div className="big-risk"><b>78</b><span>/100</span><Pill tone="danger">High attention</Pill></div></div><div className="dimension-list">{dimensions.map(d=><div key={d[0]}><div><b>{d[0]}</b><span>{d[2]}</span></div><strong>{d[1]}%</strong><i><em style={{width:`${d[1]}%`}}/></i></div>)}</div></div><div className="card analyst-review"><h3>Analyst review</h3><div className="review-state"><CircleCheck/><div><b>Evidence inspected</b><span>6 of 6 dimensions reviewed</span></div></div><label>Assessment confidence<select defaultValue="Moderate"><option>High</option><option>Moderate</option><option>Low</option></select></label><label>Analyst notes<textarea defaultValue="Identity mismatch remains unresolved. Relationship indicators are supported by address and contact records. No inference of criminal activity should be drawn without further investigation."/></label><div className="decision-note"><Shield/><span>Risk indicators provide decision support only and do not determine guilt or enforcement action.</span></div><button className="primary full" onClick={()=>toast('Analyst review recorded')}>Record analyst review</button></div></div>}

function Trends(){return <div className="trends-grid"><div className="card trend-large"><div className="analysis-subhead"><div><span>INCIDENT PATTERNS</span><h3>Category activity</h3><p>Last 12 weeks · Kano operational scope</p></div><Pill tone="danger">+8.4%</Pill></div><div className="bar-chart">{[34,51,43,69,56,74,62,87,71,93,82,100].map((v,i)=><i key={i}><em style={{height:`${v}%`}}/><span>W{i+1}</span></i>)}</div></div><div className="card hotspots"><h3>Emerging hotspots</h3>{[['Bunkure LGA','12 incidents','+21%'],['Kano Municipal','9 incidents','+12%'],['Dala LGA','7 incidents','−4%'],['Tarauni LGA','6 incidents','+8%']].map((h,i)=><div key={h[0]}><span>{i+1}</span><div><b>{h[0]}</b><small>{h[1]}</small></div><strong>{h[2]}</strong></div>)}</div><div className="card pattern-findings"><h3>Detected patterns</h3>{[['Repeated location cluster','4 incidents within 3 km over 10 days','high'],['Shared contact identifier','2 monitored subjects use matching telephone','medium'],['Recurring travel route','Kano–Maradi route observed 6 times','medium']].map(p=><button key={p[0]}><Activity/><div><b>{p[0]}</b><span>{p[1]}</span></div><Pill tone={p[2]==='high'?'danger':'warning'}>{p[2]}</Pill><ChevronRight/></button>)}</div></div>}

export default function Analysis({toast}:{toast:Toast}){const [tab,setTab]=useState<'map'|'risk'|'trends'>('map');return <><section className="page-title module-title"><div><p>INTELLIGENCE FORESIGHT</p><h1>Analysis workspace</h1><span>Explore relationships, patterns, and explainable evidence across authorized records.</span></div><button className="primary" onClick={()=>toast('New analysis collection created')}><Plus/> New analysis</button></section><div className="analysis-tabs"><button className={tab==='map'?'active':''} onClick={()=>setTab('map')}><GitFork/> Relationship map</button><button className={tab==='risk'?'active':''} onClick={()=>setTab('risk')}><Gauge/> Behavioral risk</button><button className={tab==='trends'?'active':''} onClick={()=>setTab('trends')}><Activity/> Patterns & trends</button></div>{tab==='map'?<RelationshipMap toast={toast}/>:tab==='risk'?<RiskAnalysis toast={toast}/>:<Trends/>}</>}
